### PR TITLE
chore: clean up repo

### LINKED ISSUE #6: feat: import existing designs
### Description
Import existing designs into this repo.

### Requirements

- [x] VCU
- [x] TSAL
- [x] HV sense
- [x] BSPD
- [x] Discharge
- [x] Latching
- [x] Precharge.

### LINKED ISSUE #10: chore(bspd): remove version number from project/schematic file names
### Description
Don't need the version numbers in the file name - that's what we have version control for!

### LINKED ISSUE #12: chore(precharge): move symbols, footprints and step files to shared library
### Description
Move symbols, footprints and step files in precharge to shared library.
This will require the library paths to be updated.

### PR DESCRIPTION
**Pull request by Mxrxk**
### Changes
- List of main changes.

### Related Issue(s)
Closes #6 
Closes #12 
Closes #10 

### Checklist
- [x] ERC passes with no errors.
- [x] DRC passes with no errors.
- [x] No files which should not be under version control added (see [README](https://github.com/sufst/pcb/blob/main/README.md)).
- [x] Library paths are relative paths.

### Additional Notes
Any additional notes.

### CODE REVIEW

**Comment by t-bre** [comment]
@Mxrxk see when you have a commit with a very long message like:

```
chore(all) renamed BSPD files to remove version number from name, moved all symbols from individual symbol libraries into common/sufts-lib.kicad_sym, combined all project specific footprint folders into common/sufts-lib.pretty, moved all project specific step files into common/step, fixed all paths making them relative, fixed all broken cad models on pcbs. missing one cad model that is simply impossible to find online. imported discharge relay breakout pcb folder.
```

Every thing separated by a ',' should really be a separate commit. I think the convention is ideally to keep commit messages less than 80 characters (though I wouldn't call that a hard rule, I just go for "keep it short"). Another possibility would be to create a summary message describing the overall change like "chore: clean up old designs" and then put all those points into the extended description as a list. Personally I just go for making a large number of commits and then doing a squash merge at the end, it takes like 10 seconds to make a commit so I don't find it to be a huge pain.

I'd also suggest that one pull request should have one specific focus. This one is a bit weird because there's the update to the BSPD, plus a bunch of cleanup of all the old designs. So I'd probably make this two pull requests, one for the BSPD and one for the cleanup (in this case let's just leave it, but in future!).

**Review by t-bre — CHANGES_REQUESTED** [review]
Possibly needs changed:
- `precharge` 3D models don’t appear for me, but they appear to have valid paths?
- Not sure if some of the `precharge` simulations should have been deleted?
- PS1 is missing 3D model in `hv-sense` for me

Change later:
- Eventually would be good to add who originally drew schematics, don’t need to fix that right away. Maybe make an issue and look at it later.

**Comment by t-bre** [comment]
Also would be good to fill out the details in the PR template (quick summary, which issues are closed, checklist).

**Comment by t-bre** [comment]
Also also, make sure to create your branch out of `main`. This one was created out of the `test` branch which has a random test commit at the start. You just have to switch to `main` before creating the branch.

Screenshot 2022-12-11 at 14 01 37

**Comment by Mxrxk** [comment]
> Possibly needs changed:
> 
> * `precharge` 3D models don’t appear for me, but they appear to have valid paths?
> * Not sure if some of the `precharge` simulations should have been deleted?
> * PS1 is missing 3D model in `hv-sense` for me
> 
> Change later:
> 
> * Eventually would be good to add who originally drew schematics, don’t need to fix that right away. Maybe make an issue and look at it later.

image

- I had the same issue with `precharge`. Double check the last 3 icons are checked to see if all components show or not. Otherwise I'm not sure what the issue could be. Also try deleting the footprints path and putting it back in, that seemed to have fixed it for me earlier.

- I think I might have accidentally removed the simulations from the folder. Ill add them back now.

- PS1 CAD simply doesn't exist anywhere on the internet so ill make it myself and place it in over Christmas.

- When I was adding the templates in I wasn't sure who had originally designed the PCBs so I left the fields blank. We'll track it down later but for now I'll make an issue.

**Pull request merged**
