### PR TITLE
feat(ail): add copper pour to MOSFET drains

### PR DESCRIPTION
**Pull request by t-bre**
### Changes
- Adds a copper pour to the MOSFET drains to try and improve thermal performance.
- Removes a bridging resistor that is no longer necessary.

### Checklist
- [x] ERC passes with no errors.
- [x] DRC passes with no errors.
- [x] No files which should not be under version control added (see [README](https://github.com/sufst/pcb/blob/main/README.md)).
- [x] Library paths are relative paths.

### CODE REVIEW

**Comment by t-bre** [comment]
@saltyboi2995 could you take a look at this and make sure you're happy. I'm also now getting a clearance violation on the DRC after Max added the copper pour - if you could possibly take a look at that too please that'd be great!

**Comment by saltyboi2995** [comment]
I didn't see a pour under the mosfets, was it removed afterwards?
image

**Comment by t-bre** [comment]
I've fixed the violation, check latest commit.

I think it should be fine now, but it would be good to check the DRC configuration against JLC's specs.

**Comment by t-bre** [comment]
> I didn't see a pour under the mosfets, was it removed afterwards?

Looks like you're on the old `tsac-dev` branch? That has been merged, this is a new branch `fix/ail` that Max made I'd double check that you're on it.

**Comment by saltyboi2995** [comment]
> > I didn't see a pour under the mosfets, was it removed afterwards?
> 
> Looks like you're on the old `tsac-dev` branch? That has been merged, this is a new branch `fix/ail` that Max made I'd double check that you're on it.

Yep, I was on the wrong branch. Looks good, just need to figure out how to configure the DRC

**Comment by saltyboi2995** [comment]
Also, since this PCB will need to be assembled on a reflow plate, should I remove the thermal relief on the mosfets to increase heat transfer?

**Comment by t-bre** [comment]
JLC has loads of info on their website about the DRC (I think the "capabilities" page). I'm not sure how accurately other projects are configured to the JLC spec (though we haven't had any problems) so it's probably worth just going through it from scratch.

One not to change if possible (i.e. if it meets JLC spec) is the "copper to edge clearance". I believe Max set that as a quick way to create some space between the copper pour and the board edge. I guess if anything is set to something more strict than JLC specs, just leave it. But if it is less than the spec, update it and re-run the DRC.

Screenshot 2023-04-19 at 15 19 54

**Comment by t-bre** [comment]
> Also, since this PCB will need to be assembled on a reflow plate, should I remove the thermal relief on the mosfets to increase heat transfer?

Yeah sounds like a good idea.

**Comment by saltyboi2995** [comment]
Annoyingly almost all the silkscreens for the component numbers are 0.15mm but JLC has a minimum of 0.153, will that be an issue?

**Comment by t-bre** [comment]
> Annoyingly almost all the silkscreens for the component numbers are 0.15mm but JLC has a minimum of 0.153, will that be an issue?

I'm pretty sure that will be fine. I assume the silkscreens for the reference designators are the default size, which I've never had an issue with.

**Review by saltyboi2995 — APPROVED** [review]

**Pull request merged**
